// test-data.js

const testData = {
  "Hematology": [
    { name: "Hemoglobin (Hb)", unit: "g/dL", range: "13.5-17.5 (M), 12-16 (F)" },
    { name: "Total Leukocyte Count (WBC)", unit: "/mm³", range: "4000-11000" },
    { name: "Platelet Count", unit: "/mm³", range: "150000-450000" },
    { name: "Packed Cell Volume (PCV)", unit: "%", range: "40-54 (M), 36-46 (F)" },
    { name: "RBC Count", unit: "millions/µL", range: "4.5-6.0 (M), 4.0-5.5 (F)" },
    { name: "MCV", unit: "fL", range: "80-100" },
    { name: "MCH", unit: "pg", range: "27-32" },
    { name: "MCHC", unit: "g/dL", range: "32-36" },
    { name: "RDW", unit: "%", range: "11.5-14.5" },
    { name: "ESR", unit: "mm/hr", range: "0-15 (M), 0-20 (F)" },
    { name: "Differential Count - Neutrophils", unit: "%", range: "40-70" },
    { name: "Differential Count - Lymphocytes", unit: "%", range: "20-40" },
    { name: "Differential Count - Monocytes", unit: "%", range: "2-8" },
    { name: "Differential Count - Eosinophils", unit: "%", range: "1-6" },
    { name: "Differential Count - Basophils", unit: "%", range: "0-1" },
    { name: "Reticulocyte Count", unit: "%", range: "0.5-1.5" },
    { name: "Clotting Time", unit: "min", range: "4-10" },
    { name: "Bleeding Time", unit: "min", range: "2-7" },
    { name: "Peripheral Blood Smear", unit: "N/A", range: "Normal morphology" },
    { name: "Bone Marrow Examination", unit: "N/A", range: "Normal cellularity" }
  ],

  "Biochemistry": [
    { name: "Fasting Blood Sugar (FBS)", unit: "mg/dL", range: "70-100" },
    { name: "Random Blood Sugar (RBS)", unit: "mg/dL", range: "< 140" },
    { name: "HbA1c", unit: "%", range: "4.0-5.6" },
    { name: "Urea", unit: "mg/dL", range: "15-40" },
    { name: "Creatinine", unit: "mg/dL", range: "0.6-1.3" },
    { name: "Uric Acid", unit: "mg/dL", range: "3.4-7.0" },
    { name: "Cholesterol - Total", unit: "mg/dL", range: "< 200" },
    { name: "HDL Cholesterol", unit: "mg/dL", range: "> 40" },
    { name: "LDL Cholesterol", unit: "mg/dL", range: "< 130" },
    { name: "Triglycerides", unit: "mg/dL", range: "< 150" },
    { name: "Calcium", unit: "mg/dL", range: "8.5-10.5" },
    { name: "Phosphorus", unit: "mg/dL", range: "2.5-4.5" },
    { name: "Magnesium", unit: "mg/dL", range: "1.6-2.6" },
    { name: "Sodium", unit: "mmol/L", range: "135-145" },
    { name: "Potassium", unit: "mmol/L", range: "3.5-5.0" },
    { name: "Chloride", unit: "mmol/L", range: "98-107" },
    { name: "Bicarbonate", unit: "mmol/L", range: "22-28" },
    { name: "Total Protein", unit: "g/dL", range: "6.0-8.3" },
    { name: "Albumin", unit: "g/dL", range: "3.5-5.0" },
    { name: "Globulin", unit: "g/dL", range: "2.0-3.5" }
  ],
  "Serology": [
    { name: "HIV Antibody Test", unit: "N/A", range: "Non-reactive" },
    { name: "Hepatitis B Surface Antigen (HBsAg)", unit: "N/A", range: "Negative" },
    { name: "Hepatitis C Antibody (Anti-HCV)", unit: "N/A", range: "Negative" },
    { name: "VDRL (Syphilis)", unit: "N/A", range: "Non-reactive" },
    { name: "Widal Test (Typhoid)", unit: "titer", range: "< 1:80" },
    { name: "ASO Titer", unit: "IU/mL", range: "< 200" },
    { name: "CRP (C-Reactive Protein)", unit: "mg/L", range: "< 6" },
    { name: "Rheumatoid Factor (RF)", unit: "IU/mL", range: "< 14" },
    { name: "ANA (Antinuclear Antibody)", unit: "N/A", range: "Negative" },
    { name: "Dengue NS1 Antigen", unit: "N/A", range: "Negative" },
    { name: "Dengue IgM Antibody", unit: "N/A", range: "Negative" },
    { name: "Dengue IgG Antibody", unit: "N/A", range: "Negative" },
    { name: "Malaria Antigen Test", unit: "N/A", range: "Negative" },
    { name: "Covid-19 Rapid Antigen", unit: "N/A", range: "Negative" },
    { name: "Covid-19 IgM", unit: "N/A", range: "Negative" },
    { name: "Covid-19 IgG", unit: "N/A", range: "Negative" },
    { name: "Toxoplasma IgM", unit: "N/A", range: "Negative" },
    { name: "Toxoplasma IgG", unit: "N/A", range: "Negative" },
    { name: "Rubella IgM", unit: "N/A", range: "Negative" },
    { name: "Rubella IgG", unit: "N/A", range: "Positive (immune)" }
  ],

  "Microbiology": [
    { name: "Urine Culture & Sensitivity", unit: "N/A", range: "No growth" },
    { name: "Blood Culture & Sensitivity", unit: "N/A", range: "No growth" },
    { name: "Sputum Culture & Sensitivity", unit: "N/A", range: "No growth" },
    { name: "Throat Swab Culture", unit: "N/A", range: "No pathogenic growth" },
    { name: "Stool Culture", unit: "N/A", range: "No pathogenic growth" },
    { name: "CSF Culture", unit: "N/A", range: "No growth" },
    { name: "Wound Swab Culture", unit: "N/A", range: "No pathogenic growth" },
    { name: "H. Pylori Antigen (Stool)", unit: "N/A", range: "Negative" },
    { name: "H. Pylori Antibody (Blood)", unit: "N/A", range: "Negative" },
    { name: "AFB (Sputum Smear for TB)", unit: "N/A", range: "Negative" },
    { name: "Gram Stain", unit: "N/A", range: "Normal flora" },
    { name: "KOH Mount (Fungal)", unit: "N/A", range: "No fungal elements" },
    { name: "Fungal Culture", unit: "N/A", range: "No growth" },
    { name: "Chlamydia Antigen", unit: "N/A", range: "Negative" },
    { name: "Gonorrhea Antigen", unit: "N/A", range: "Negative" },
    { name: "Influenza A Antigen", unit: "N/A", range: "Negative" },
    { name: "Influenza B Antigen", unit: "N/A", range: "Negative" },
    { name: "Mycoplasma Pneumoniae Antibody", unit: "N/A", range: "Negative" },
    { name: "Leptospira Antibody", unit: "N/A", range: "Negative" },
    { name: "Salmonella Antibody Test", unit: "N/A", range: "Negative" }
  ],
  "Urine": [
    { name: "Urine Routine Examination", unit: "N/A", range: "Normal" },
    { name: "Urine pH", unit: "pH", range: "4.5 - 8.0" },
    { name: "Urine Specific Gravity", unit: "g/mL", range: "1.005 - 1.030" },
    { name: "Urine Protein", unit: "mg/dL", range: "Negative" },
    { name: "Urine Glucose", unit: "mg/dL", range: "Negative" },
    { name: "Urine Ketones", unit: "mg/dL", range: "Negative" },
    { name: "Urine Bilirubin", unit: "mg/dL", range: "Negative" },
    { name: "Urine Urobilinogen", unit: "mg/dL", range: "0.2 - 1.0" },
    { name: "Urine Microscopy (RBCs)", unit: "/HPF", range: "0 - 2" },
    { name: "Urine Microscopy (WBCs)", unit: "/HPF", range: "0 - 5" },
    { name: "Urine Casts", unit: "N/A", range: "Absent" },
    { name: "Urine Crystals", unit: "N/A", range: "Absent" },
    { name: "Urine Nitrite", unit: "N/A", range: "Negative" },
    { name: "Urine Color", unit: "N/A", range: "Pale Yellow" },
    { name: "Urine Appearance", unit: "N/A", range: "Clear" },
    { name: "Urine Leukocyte Esterase", unit: "N/A", range: "Negative" },
    { name: "Urine Microalbumin", unit: "mg/L", range: "< 30" },
    { name: "Urine Culture & Sensitivity", unit: "N/A", range: "No growth" },
    { name: "Urine Osmolality", unit: "mOsm/kg", range: "300 - 900" },
    { name: "Urine Chloride", unit: "mmol/L", range: "110 - 250" }
  ],

  "Stool": [
    { name: "Stool Routine Examination", unit: "N/A", range: "Normal" },
    { name: "Stool Occult Blood", unit: "N/A", range: "Negative" },
    { name: "Stool Ova & Parasites", unit: "N/A", range: "Absent" },
    { name: "Stool Cysts", unit: "N/A", range: "Absent" },
    { name: "Stool RBCs", unit: "/HPF", range: "Absent" },
    { name: "Stool WBCs", unit: "/HPF", range: "Absent" },
    { name: "Stool Color", unit: "N/A", range: "Brown" },
    { name: "Stool Consistency", unit: "N/A", range: "Formed" },
    { name: "Stool Fat (Sudan Stain)", unit: "N/A", range: "Negative" },
    { name: "Stool Reducing Substances", unit: "mg/dL", range: "< 0.5" },
    { name: "Stool Helicobacter pylori Antigen", unit: "N/A", range: "Negative" },
    { name: "Stool Giardia Antigen", unit: "N/A", range: "Negative" },
    { name: "Stool Rotavirus Antigen", unit: "N/A", range: "Negative" },
    { name: "Stool Calprotectin", unit: "µg/g", range: "< 50" },
    { name: "Stool pH", unit: "pH", range: "6.5 - 7.5" },
    { name: "Stool Occult Blood (Immunochemical)", unit: "N/A", range: "Negative" },
    { name: "Stool Culture & Sensitivity", unit: "N/A", range: "No pathogenic growth" },
    { name: "Stool Clostridium difficile Toxin", unit: "N/A", range: "Negative" },
    { name: "Stool Cryptosporidium Antigen", unit: "N/A", range: "Negative" },
    { name: "Stool Entamoeba histolytica Antigen", unit: "N/A", range: "Negative" }
  ],

  "Liver Function Tests (LFT)": [
    { name: "Total Bilirubin", unit: "mg/dL", range: "0.3 - 1.2" },
    { name: "Direct Bilirubin", unit: "mg/dL", range: "0.1 - 0.4" },
    { name: "Indirect Bilirubin", unit: "mg/dL", range: "0.2 - 0.8" },
    { name: "SGPT (ALT)", unit: "U/L", range: "7 - 56" },
    { name: "SGOT (AST)", unit: "U/L", range: "10 - 40" },
    { name: "Alkaline Phosphatase (ALP)", unit: "U/L", range: "44 - 147" },
    { name: "Gamma GT (GGT)", unit: "U/L", range: "9 - 48" },
    { name: "Total Protein", unit: "g/dL", range: "6.0 - 8.3" },
    { name: "Albumin", unit: "g/dL", range: "3.4 - 5.4" },
    { name: "Globulin", unit: "g/dL", range: "2.0 - 3.5" },
    { name: "Albumin/Globulin Ratio", unit: "N/A", range: "1.1 - 2.5" },
    { name: "Prothrombin Time (PT)", unit: "seconds", range: "11 - 13.5" },
    { name: "INR", unit: "N/A", range: "0.8 - 1.2" },
    { name: "LDH (Lactate Dehydrogenase)", unit: "U/L", range: "140 - 280" },
    { name: "Cholinesterase", unit: "U/L", range: "5000 - 12000" },
    { name: "Prealbumin", unit: "mg/dL", range: "15 - 36" },
    { name: "Alpha-1 Antitrypsin", unit: "mg/dL", range: "90 - 200" },
    { name: "Ceruloplasmin", unit: "mg/dL", range: "20 - 60" },
    { name: "Ammonia", unit: "µmol/L", range: "15 - 45" },
    { name: "Bile Acids", unit: "µmol/L", range: "< 10" }
  ],
  "Kidney Function Tests (RFT)": [
    { name: "Blood Urea", unit: "mg/dL", range: "15 - 40" },
    { name: "Serum Creatinine", unit: "mg/dL", range: "0.6 - 1.2" },
    { name: "Uric Acid", unit: "mg/dL", range: "3.5 - 7.2" },
    { name: "Blood Urea Nitrogen (BUN)", unit: "mg/dL", range: "7 - 20" },
    { name: "BUN/Creatinine Ratio", unit: "N/A", range: "10 - 20" },
    { name: "Electrolytes - Sodium (Na⁺)", unit: "mmol/L", range: "135 - 145" },
    { name: "Electrolytes - Potassium (K⁺)", unit: "mmol/L", range: "3.5 - 5.1" },
    { name: "Electrolytes - Chloride (Cl⁻)", unit: "mmol/L", range: "98 - 107" },
    { name: "Electrolytes - Bicarbonate (HCO₃⁻)", unit: "mmol/L", range: "22 - 29" },
    { name: "Calcium (Ca²⁺)", unit: "mg/dL", range: "8.5 - 10.5" },
    { name: "Phosphorus (PO₄³⁻)", unit: "mg/dL", range: "2.5 - 4.5" },
    { name: "Magnesium (Mg²⁺)", unit: "mg/dL", range: "1.7 - 2.3" },
    { name: "Cystatin C", unit: "mg/L", range: "0.5 - 1.2" },
    { name: "eGFR (Glomerular Filtration Rate)", unit: "mL/min/1.73m²", range: "> 90" },
    { name: "Urinary Sodium", unit: "mmol/L", range: "40 - 220" },
    { name: "Urinary Potassium", unit: "mmol/L", range: "25 - 125" },
    { name: "Urinary Creatinine", unit: "mg/dL", range: "500 - 2000" },
    { name: "Microalbumin (Urine)", unit: "mg/L", range: "< 30" },
    { name: "Creatinine Clearance", unit: "mL/min", range: "90 - 140" },
    { name: "Renin Activity", unit: "ng/mL/hr", range: "0.5 - 4.0" }
  ],

  "Lipid Profile": [
    { name: "Total Cholesterol", unit: "mg/dL", range: "< 200" },
    { name: "HDL Cholesterol", unit: "mg/dL", range: "> 40" },
    { name: "LDL Cholesterol", unit: "mg/dL", range: "< 100" },
    { name: "Triglycerides", unit: "mg/dL", range: "< 150" },
    { name: "VLDL Cholesterol", unit: "mg/dL", range: "5 - 40" },
    { name: "Cholesterol/HDL Ratio", unit: "N/A", range: "< 4.5" },
    { name: "LDL/HDL Ratio", unit: "N/A", range: "< 3.0" },
    { name: "Non-HDL Cholesterol", unit: "mg/dL", range: "< 130" },
    { name: "Apolipoprotein A1", unit: "mg/dL", range: "110 - 180" },
    { name: "Apolipoprotein B", unit: "mg/dL", range: "60 - 120" },
    { name: "Apolipoprotein B/A1 Ratio", unit: "N/A", range: "< 0.7" },
    { name: "Lipoprotein (a)", unit: "mg/dL", range: "< 30" },
    { name: "Small Dense LDL", unit: "N/A", range: "Low" },
    { name: "Remnant Cholesterol", unit: "mg/dL", range: "< 20" },
    { name: "Oxidized LDL", unit: "U/L", range: "< 60" },
    { name: "Total Lipids", unit: "mg/dL", range: "400 - 1000" },
    { name: "Phospholipids", unit: "mg/dL", range: "125 - 275" },
    { name: "Free Fatty Acids", unit: "µEq/L", range: "250 - 750" },
    { name: "Beta-lipoprotein", unit: "mg/dL", range: "Normal" },
    { name: "Chylomicrons", unit: "N/A", range: "Absent" }
  ],

  "Thyroid Profile": [
    { name: "TSH (Thyroid Stimulating Hormone)", unit: "µIU/mL", range: "0.4 - 4.0" },
    { name: "Free T3", unit: "pg/mL", range: "2.3 - 4.2" },
    { name: "Free T4", unit: "ng/dL", range: "0.8 - 1.8" },
    { name: "Total T3", unit: "ng/dL", range: "80 - 200" },
    { name: "Total T4", unit: "µg/dL", range: "5.0 - 12.0" },
    { name: "Reverse T3", unit: "ng/dL", range: "10 - 24" },
    { name: "Thyroglobulin", unit: "ng/mL", range: "< 55" },
    { name: "Thyroglobulin Antibody", unit: "IU/mL", range: "< 4.0" },
    { name: "Thyroid Peroxidase Antibody (Anti-TPO)", unit: "IU/mL", range: "< 35" },
    { name: "TSI (Thyroid Stimulating Immunoglobulin)", unit: "N/A", range: "Negative" },
    { name: "Calcitonin", unit: "pg/mL", range: "< 10" },
    { name: "Thyroxine Binding Globulin (TBG)", unit: "mg/L", range: "13 - 30" },
    { name: "Thyroid Uptake Test (T3RU)", unit: "%", range: "24 - 39" },
    { name: "Thyroid Function Index (TFI)", unit: "N/A", range: "Normal" },
    { name: "Basal Metabolic Rate (BMR)", unit: "%", range: "-15 to +5" },
    { name: "FT3/FT4 Ratio", unit: "N/A", range: "Normal" },
    { name: "TSH Receptor Antibodies", unit: "IU/L", range: "< 1.5" },
    { name: "Thyroid Microsomal Antibody", unit: "IU/mL", range: "< 35" },
    { name: "Serum Iodine", unit: "µg/L", range: "40 - 90" },
    { name: "Serum Selenium", unit: "µg/L", range: "70 - 150" }
  ],
  "Diabetes / HbA1c": [
    { name: "Fasting Blood Glucose", unit: "mg/dL", range: "70 - 100" },
    { name: "Random Blood Glucose", unit: "mg/dL", range: "< 140" },
    { name: "2-Hour Post Prandial Glucose", unit: "mg/dL", range: "< 140" },
    { name: "Oral Glucose Tolerance Test (OGTT)", unit: "mg/dL", range: "< 140" },
    { name: "HbA1c", unit: "%", range: "< 5.7" },
    { name: "Estimated Average Glucose (eAG)", unit: "mg/dL", range: "70 - 126" },
    { name: "Fructosamine", unit: "µmol/L", range: "200 - 285" },
    { name: "C-Peptide (Fasting)", unit: "ng/mL", range: "0.9 - 4.0" },
    { name: "Insulin (Fasting)", unit: "µIU/mL", range: "2.6 - 24.9" },
    { name: "Insulin (Postprandial)", unit: "µIU/mL", range: "< 60" },
    { name: "HOMA-IR Index", unit: "N/A", range: "< 2.0" },
    { name: "Proinsulin", unit: "pmol/L", range: "< 10" },
    { name: "Anti-Insulin Antibodies", unit: "N/A", range: "Negative" },
    { name: "GAD65 Antibody", unit: "IU/mL", range: "< 1.0" },
    { name: "IA-2 Antibody", unit: "N/A", range: "Negative" },
    { name: "Zinc Transporter 8 Antibody (ZnT8)", unit: "N/A", range: "Negative" },
    { name: "Urinary Glucose", unit: "mg/dL", range: "Negative" },
    { name: "Ketone Bodies (Urine)", unit: "mg/dL", range: "Negative" },
    { name: "Beta-Hydroxybutyrate", unit: "mmol/L", range: "< 0.6" },
    { name: "Lactate", unit: "mmol/L", range: "0.5 - 2.2" }
  ],

  "Hormones": [
    { name: "Cortisol (AM)", unit: "µg/dL", range: "5 - 23" },
    { name: "Cortisol (PM)", unit: "µg/dL", range: "3 - 13" },
    { name: "ACTH (Adrenocorticotropic Hormone)", unit: "pg/mL", range: "10 - 60" },
    { name: "Prolactin", unit: "ng/mL", range: "3 - 20" },
    { name: "Estradiol (E2)", unit: "pg/mL", range: "15 - 350" },
    { name: "Progesterone", unit: "ng/mL", range: "0.1 - 25" },
    { name: "Testosterone (Total)", unit: "ng/dL", range: "300 - 1000 (male)" },
    { name: "Testosterone (Free)", unit: "pg/mL", range: "47 - 244" },
    { name: "LH (Luteinizing Hormone)", unit: "mIU/mL", range: "1 - 20" },
    { name: "FSH (Follicle Stimulating Hormone)", unit: "mIU/mL", range: "1 - 20" },
    { name: "DHEA-Sulfate", unit: "µg/dL", range: "35 - 430" },
    { name: "17-OH Progesterone", unit: "ng/dL", range: "20 - 200" },
    { name: "Androstenedione", unit: "ng/dL", range: "30 - 200" },
    { name: "SHBG (Sex Hormone Binding Globulin)", unit: "nmol/L", range: "18 - 114" },
    { name: "AMH (Anti-Müllerian Hormone)", unit: "ng/mL", range: "0.7 - 3.5" },
    { name: "hCG (Quantitative)", unit: "mIU/mL", range: "< 5" },
    { name: "Insulin-like Growth Factor-1 (IGF-1)", unit: "ng/mL", range: "100 - 300" },
    { name: "Growth Hormone (GH)", unit: "ng/mL", range: "< 10" },
    { name: "Melatonin", unit: "pg/mL", range: "10 - 80" },
    { name: "Aldosterone", unit: "ng/dL", range: "4 - 31" }
  ],

  "Cardiac Markers": [
    { name: "Troponin I", unit: "ng/mL", range: "< 0.04" },
    { name: "Troponin T", unit: "ng/mL", range: "< 0.01" },
    { name: "CK-MB", unit: "ng/mL", range: "< 5" },
    { name: "Total CK (Creatine Kinase)", unit: "U/L", range: "30 - 170" },
    { name: "Myoglobin", unit: "ng/mL", range: "25 - 72" },
    { name: "BNP (B-type Natriuretic Peptide)", unit: "pg/mL", range: "< 100" },
    { name: "NT-proBNP", unit: "pg/mL", range: "< 125" },
    { name: "hs-CRP (Cardiac Risk)", unit: "mg/L", range: "< 1.0" },
    { name: "Homocysteine", unit: "µmol/L", range: "4 - 15" },
    { name: "Lipoprotein-associated Phospholipase A2 (Lp-PLA2)", unit: "ng/mL", range: "< 200" },
    { name: "Ischemia Modified Albumin (IMA)", unit: "U/mL", range: "< 85" },
    { name: "Copeptin", unit: "pmol/L", range: "< 10" },
    { name: "Galectin-3", unit: "ng/mL", range: "< 17.8" },
    { name: "ST2 (Suppression of Tumorigenicity 2)", unit: "ng/mL", range: "< 35" },
    { name: "CK Index", unit: "N/A", range: "< 2.5" },
    { name: "LDH Isoenzymes", unit: "N/A", range: "Normal pattern" },
    { name: "Glycogen Phosphorylase Isoenzyme BB (GPBB)", unit: "ng/mL", range: "Normal" },
    { name: "Heart-type Fatty Acid Binding Protein (H-FABP)", unit: "ng/mL", range: "< 6.0" },
    { name: "MicroRNA-208", unit: "N/A", range: "Negative" },
    { name: "Oxidative Stress Marker (MDA)", unit: "µmol/L", range: "< 3.0" }
  ],
  "Tumor Markers": [
    { name: "Alpha-Fetoprotein (AFP)", unit: "ng/mL", range: "< 10" },
    { name: "Carcinoembryonic Antigen (CEA)", unit: "ng/mL", range: "< 3.0" },
    { name: "CA-125", unit: "U/mL", range: "< 35" },
    { name: "CA-19-9", unit: "U/mL", range: "< 37" },
    { name: "CA-15-3", unit: "U/mL", range: "< 30" },
    { name: "PSA (Total)", unit: "ng/mL", range: "< 4.0" },
    { name: "PSA (Free/Total Ratio)", unit: "Ratio", range: "> 0.25" },
    { name: "Beta-hCG (Tumor Marker)", unit: "mIU/mL", range: "< 5" },
    { name: "Thyroglobulin", unit: "ng/mL", range: "< 55" },
    { name: "Calcitonin", unit: "pg/mL", range: "< 10" },
    { name: "NSE (Neuron Specific Enolase)", unit: "ng/mL", range: "< 16" },
    { name: "CYFRA 21-1", unit: "ng/mL", range: "< 3.3" },
    { name: "SCC Antigen", unit: "ng/mL", range: "< 2.0" },
    { name: "HE4 (Human Epididymis Protein 4)", unit: "pmol/L", range: "< 140" },
    { name: "LDH (Tumor Marker)", unit: "U/L", range: "100 - 190" },
    { name: "Chromogranin A", unit: "ng/mL", range: "< 100" },
    { name: "ProGRP (Pro-Gastrin Releasing Peptide)", unit: "pg/mL", range: "< 80" },
    { name: "BLCA-4 (Bladder Cancer Marker)", unit: "N/A", range: "Negative" },
    { name: "MUC1", unit: "U/mL", range: "Normal" },
    { name: "p53 Antibody", unit: "N/A", range: "Negative" }
  ],

  "Infectious Diseases": [
    { name: "HIV 1/2 Antibody", unit: "N/A", range: "Non-Reactive" },
    { name: "HIV RNA PCR", unit: "copies/mL", range: "Not Detected" },
    { name: "Hepatitis B Surface Antigen (HBsAg)", unit: "N/A", range: "Negative" },
    { name: "Hepatitis B Surface Antibody (Anti-HBs)", unit: "mIU/mL", range: "> 10" },
    { name: "Hepatitis B Core Antibody (Anti-HBc)", unit: "N/A", range: "Negative" },
    { name: "Hepatitis C Antibody (Anti-HCV)", unit: "N/A", range: "Negative" },
    { name: "HCV RNA PCR", unit: "IU/mL", range: "Not Detected" },
    { name: "Hepatitis A IgM", unit: "N/A", range: "Negative" },
    { name: "Hepatitis E IgM", unit: "N/A", range: "Negative" },
    { name: "Syphilis (VDRL/RPR)", unit: "N/A", range: "Non-Reactive" },
    { name: "TPHA (Treponema Pallidum Hemagglutination)", unit: "N/A", range: "Negative" },
    { name: "Malaria Parasite (MP Smear)", unit: "N/A", range: "Not Seen" },
    { name: "Dengue NS1 Antigen", unit: "N/A", range: "Negative" },
    { name: "Dengue IgM", unit: "N/A", range: "Negative" },
    { name: "Dengue IgG", unit: "N/A", range: "Negative" },
    { name: "Typhoid (Widal Test)", unit: "Titre", range: "< 1:80" },
    { name: "TB (Mantoux Test)", unit: "mm", range: "< 10" },
    { name: "TB PCR", unit: "N/A", range: "Not Detected" },
    { name: "COVID-19 PCR", unit: "N/A", range: "Not Detected" },
    { name: "COVID-19 IgM/IgG", unit: "N/A", range: "Negative" }
  ],

  "Immunology / Autoimmune": [
    { name: "ANA (Antinuclear Antibody)", unit: "N/A", range: "Negative" },
    { name: "Anti-dsDNA", unit: "IU/mL", range: "< 30" },
    { name: "Anti-Smith Antibody", unit: "N/A", range: "Negative" },
    { name: "Anti-RNP Antibody", unit: "N/A", range: "Negative" },
    { name: "Anti-Ro (SSA)", unit: "N/A", range: "Negative" },
    { name: "Anti-La (SSB)", unit: "N/A", range: "Negative" },
    { name: "Rheumatoid Factor (RF)", unit: "IU/mL", range: "< 14" },
    { name: "Anti-CCP (Cyclic Citrullinated Peptide)", unit: "U/mL", range: "< 20" },
    { name: "HLA-B27", unit: "N/A", range: "Negative" },
    { name: "ANCA (Anti-Neutrophil Cytoplasmic Antibody)", unit: "N/A", range: "Negative" },
    { name: "C3 Complement", unit: "mg/dL", range: "90 - 180" },
    { name: "C4 Complement", unit: "mg/dL", range: "10 - 40" },
    { name: "IgG", unit: "mg/dL", range: "700 - 1600" },
    { name: "IgA", unit: "mg/dL", range: "70 - 400" },
    { name: "IgM", unit: "mg/dL", range: "40 - 230" },
    { name: "IgE (Total)", unit: "IU/mL", range: "< 100" },
    { name: "Anti-Phospholipid Antibody", unit: "N/A", range: "Negative" },
    { name: "Lupus Anticoagulant", unit: "N/A", range: "Negative" },
    { name: "Beta-2 Glycoprotein Antibody", unit: "N/A", range: "Negative" },
    { name: "Cryoglobulins", unit: "N/A", range: "Absent" }
  ],
  "Vitamins & Minerals": [
    { name: "Vitamin A", unit: "µg/dL", range: "30 - 80" },
    { name: "Vitamin B1 (Thiamine)", unit: "nmol/L", range: "70 - 180" },
    { name: "Vitamin B2 (Riboflavin)", unit: "nmol/L", range: "5 - 50" },
    { name: "Vitamin B3 (Niacin)", unit: "µg/mL", range: "0.5 - 8.5" },
    { name: "Vitamin B6 (Pyridoxine)", unit: "nmol/L", range: "20 - 125" },
    { name: "Vitamin B9 (Folate)", unit: "ng/mL", range: "3 - 20" },
    { name: "Vitamin B12", unit: "pg/mL", range: "200 - 900" },
    { name: "Vitamin C", unit: "mg/dL", range: "0.6 - 2.0" },
    { name: "Vitamin D (25-OH)", unit: "ng/mL", range: "30 - 100" },
    { name: "Vitamin E", unit: "mg/L", range: "5 - 20" },
    { name: "Vitamin K", unit: "ng/mL", range: "0.2 - 3.2" },
    { name: "Calcium (Serum)", unit: "mg/dL", range: "8.5 - 10.5" },
    { name: "Ionized Calcium", unit: "mmol/L", range: "1.1 - 1.3" },
    { name: "Phosphorus", unit: "mg/dL", range: "2.5 - 4.5" },
    { name: "Magnesium", unit: "mg/dL", range: "1.7 - 2.2" },
    { name: "Zinc", unit: "µg/dL", range: "70 - 120" },
    { name: "Copper", unit: "µg/dL", range: "70 - 140" },
    { name: "Selenium", unit: "µg/L", range: "70 - 150" },
    { name: "Chromium", unit: "µg/L", range: "0.1 - 0.5" },
    { name: "Manganese", unit: "µg/L", range: "0.4 - 1.0" }
  ]
};
